### ISSUE TITLE
Wrong output of label (Firefox, Chrome)

### ISSUE THREAD

**Issue by JAWS-test** [FreedomScientific/VFO-standards-support#250]
### Summary

Wrong output of label (Firefox, Chrome)

1. save as HTML file:
```
<!DOCTYPE html>
<html lang="en">
	<head>
		<meta charset="utf-8">
		<title>label</title>
	</head>
	<body>
		before
		<label for=1>test</label>
		<input id=1>
		after
	</body>
</html>
```
2. Navigate with arrow keys

### Expected result

Output text before the label, then output of the label and input field, and then text after the label.

### Actual result

* IE 11: correct
* Chrome and Firefox: Label is output multiple times
* Firefox: Label is output as clickable
* Chrome and Firefox: Text before and after is output together with the label

#### IE 11
"before 
test
Edit
after"

#### Firefox
"before test clickable 
test
test Edit
Type in text.
after"

#### Chrome 
"before test
before test after Edit"

#### JAWS version and build number

JAWS 2019.1907.42
 
#### Operating System and version

Windows 8

#### Browser and version:

Internet Explorer 11.0.9600.19431
Chrome 76.0.3809.100
Firefox 68.0.2

**Comment by lamador** [comment]
Fixed in JAWS 2020.2008.24 on Windows 10 using Chrome 86.0.4240.75, Firefox 81.0.2, and IE11 11.1139.18362.0.

**Comment by JAWS-test** [comment]
Have tested with the same version of JAWS as you @lamador. The problem was only partially resolved. "clickable" is no longer output. Multiple output continues to occur. Also note that when navigating backwards (up arrow key), the input field is output without a label. Please reopen the issue.

## Firefox:

before **test 
test
test** edit
after

## Chrome + Edge

before **test 
test** edit
after

##  IE 11

before
**test
edit test edit**
after
