### ISSUE TITLE
JAWS is not narrating aria-describedby for treeitem

### ISSUE THREAD

**Issue by kolaps33** [FreedomScientific/VFO-standards-support#559]
### Summary

> Brief description of the issue. Please list any specific steps.
> 
> Example:
1. Go to https://w7bsz.csb.app/
2. Navigate to the tree on the page
3. On the tree item "House Lannister" press enter to expand it
4.  Navigate to the "Tywin" treeitem and press enter to expand it5
5. Navigate to Jaime or to Cersei or to Tyrion
6. observe JAWS narration

### Expected result
level2
Jaime
1 of 3
has context menu

### Actual result
level2
Jaime
1 of 3

What actually did happen?
In the fact JAWS is not narrating aria-describedby prop which is on the treeitem. 
Aria-describedby refers to the element, which has the text "has context menu".

What is interesting that in this scenario JAWS narrates aria-describedby, like:
1. Navigate to Jaime 
2. Press Shift + TAB
3. Press TAB key navigate back to the treeitem
Then JAWS is narrating aria-describedby attribute.

### Example
https://w7bsz.csb.app/
Code for the example:
https://codesandbox.io/s/fluent-ui-example-forked-w7bsz?file=/example.js

#### JAWS version and build number
2021.2103.174

#### Operating System and version
Win10 enterprise
10.0.19043

#### Browser and version:
Chrome
Version 92.0.4515.107 (Official Build) (64-bit)

**Comment by menovak** [comment]
From the given URL (#1 above) and as tested using Chrome 92/NVDA 2021.2, the treeitems with aria-describedby announce as shown below when expanded (space key) and arrow up/down:

level 2  Tywin  expanded  1 of 2
level 3  Jaime  has context menu  1 of 3
Cersei  has context menu  2 of 3  level 3
Tyrion  has context menu  3 of 3  level 3

However, using JAWS 2021.2011.16 the following announcements were recorded:

Tywin open  
level 2
Jaime  
1 of 3
Cersei  
Tyrion

**Comment by MichaelKetting** [comment]
@stevefaulkner I have also just run into this issue with JAWS 2024. I also checked the backlog and there seems to be several issues with `aria-describedby` in different scenarios. Do you have an ETA on getting the treeitem issue solved in JAWS? NVDA does it correctly.

**Comment by stevefaulkner** [comment]
@MichaelKetting will review

**Comment by antrayner** [comment]
Hi, are there any updates related to this issue? We have tested with JAWS 2025 and latest Chrome, and the issue still persists.

Thanks,
Anthony
