### ISSUE TITLE
Live region spoken in default language

### ISSUE THREAD

**Issue by bart-simons** [FreedomScientific/VFO-standards-support#8]
### Summary

My OS and JAWS are Dutch. Automatic language detection is switched on. Synthesizer is vocalizer expressive.
When I go to a page with lang="en", its contents is correctly spoken with the English voice. But when the contents of a live region is spoken, this is done with the default (Dutch) voice instead of the English one.

1. Go to https://www.gov.uk/
2. type "water" in the search field and submit
3. Under "filter by": check a check box 
4. wait until JAWS reads the contents of the live region. It says something like "684 results found "

### Expected result

"684 results found" to be read with the same English voice that is reading all the other contents on this web page

### Actual result

"684 results found" is spoken with the default voice (In my case Belgian Dutch Ellen)

#### JAWS version and build number

JAWS 18.0.4104 (but the issue is not specific for this version)

#### Operating System and version

Windows 7 64-bit

#### Browser and version:

IE11 and also in Firefox 56

**Comment by bart-simons** [comment]
Another thing that is not read with the English voice is the contents of an aria-labelledby. On gov.uk there is a section with an aria-labelledby that refers to the text Services and information. These words are not spoken with the English voice but with the JAWS default voice (Dutch in my case)

**Comment by hanshillen** [comment]
I've confirmed this issue. I noticed that the role and state information for the checkboxes ("selectievakje, niet geselecteerd") is incorrectly announced using the English voice as well. 

I have created a [test case](https://codepen.io/hhillen/pen/aLXYNv) and have filed this issue (combined with #9) internally as bug 97133: "Dutch JAWS does uses incorrect voice when announcing English content".

**Comment by JAWS-test** [comment]
The problem persists in JAWS 2019 with the current versions of Chrome, Firefox, and IE 11.
* Both the lang attribute of the entire document (on the html element) is ignored
* as well as the lang attribute within the live region.

Output is in the default JAWS language.

Tested with:
```
<!DOCTYPE html>
<html lang="en">
	<head>
		<meta charset="utf-8">
		<title>live region</title>
	</head>
	<body>
		<div role=status id=1>
		</div>
		<button onClick="document.getElementById('1').innerHTML='This is a message <p lang=fr>Ceci est un message</p> <p lang=de>Das ist eine Meldung</p> <p lang=it>Questo &egrave; un messaggio</p>';">start</button>
	</body>
</html> 
```

**Comment by bart-simons** [comment]
An easy place to test it is https://support.freedomscientific.com/Training/Surfs-Up/AriaLiveRegions.htm
Every ten seconds a new sentence is spoken with the default JAWS voice, instead of with the English voice as is indicated by the lang attribute in the html element

**Comment by TPGJRogers** [comment]
Confirmed as fixed in JAWS 2022

**Comment by helenxuyang** [comment]
Hello! I'm using JAWS 2023 and am still having issues with this. I modified the [W3 alert example](https://www.w3.org/WAI/ARIA/apg/patterns/alert/examples/alert/) and created a codepen with lang="es" to test: https://codepen.io/85halfnotes/pen/WNYpMRv

Using JAWS in Chrome, on my first press of the button, JAWS reads the alert incorrectly with the English voice. On subsequent presses, it reads correctly with the Spanish voice. Navigating onto the alert also reads correctly in Spanish. Am I doing something wrong in this example, or was this issue not fully fixed?

**Comment by JAWS-test** [comment]
@helenxuyang I have the same result with your example. I think the bug was not completely fixed by JAWS
